name: 📱 Compilar App Cordova (Pro)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Descargar código HTML
        uses: actions/checkout@v4  # <-- Actualizado a v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4 # <-- Actualizado a v4
        with:
          node-version: '20'

      - name: ☕ Configurar Java 17
        uses: actions/setup-java@v5 # <-- Actualizado a v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🛠️ Instalar Cordova y Plugins
        run: |
          npm install -g cordova
          cordova create app com.cyber.fbmanager "FB Manager"
          cp index.html app/www/index.html
          cd app
          cordova platform add android
          cordova plugin add cordova-plugin-statusbar
          cordova plugin add cordova-plugin-file
          cordova plugin add cordova-plugin-android-permissions
          cordova plugin add cordova-plugin-x-socialsharing

      - name: 🏗️ Compilar APK
        run: |
          cd app
          cordova build android --release

      - name: 📦 Subir APK Final
        uses: actions/upload-artifact@v4
        with:
          name: App_FB_Manager_Final
          path: app/platforms/android/**/*.apk
